import type { Metadata } from "next";
import "./globals.css";
import { CartProvider } from "./utils/ContextReducer";

export const metadata: Metadata = {
  title: "Dreamy Desserts",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <CartProvider>
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
    </CartProvider>
  );
}
